glob: "**/*.erb"

linters:
  Rubocop:
    enabled: true
  MissingTranslation:
    enabled: false
  ContentSecurityPolicy:
    enabled: false
  RequireInputAutocomplete:
    enabled: false
  RequireInputHelpers:
    enabled: false
